---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "denoising_nlmeans"
description: denoise a dataset with the Non Local Means algorithm
keywords:
  - nifti
  - denoising
  - nlmeans
  - scilpy
tools:
  - "scilpy":
      description: "Scilpy library"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - image:
      type: file
      description: Nifti image file to denoise
      pattern: "*.{nii,nii.gz}"

  - mask:
      type: file
      description: Nifti image file used to mask the input image
      pattern: "*.{nii,nii.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  
  - image:
      type: file
      description: Denoised Nifti image file
      pattern: "*_denoised.{nii,nii.gz}"

authors:
  - "@scilus"
