---
name: "registration_synthregistration"
description: Perform registration using SynthMorph from Freesurfer. Output transforms in Freesurfer format .lta for affine and .mgz for deform, which can be converted for ANTs with respectively lta_convert and mri_warp_convert.
keywords:
  - registration
  - Brain imaging
  - MRI
tools:
  - "Freesurfer":
      description: "Freesurfer Synthmorph"
      homepage: "https://martinos.org/malte/synthmorph/"


input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - moving:
      type: file
      description: Nifti volume moving for registration
      pattern: "*.{nii,nii.gz}"

  - fixed:
      type: file
      description: Nifti volume fixed for registration
      pattern: "*.{nii,nii.gz}"

  - fs_license:
      type: file
      description: The path to your FreeSurfer license. To get one, go to https://surfer.nmr.mgh.harvard.edu/registration.html. Optional. If you have already set your license as prescribed by Freesurfer (copied to a .license file in your $FREESURFER_HOME), this is not required.
      pattern: "*.txt"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - init_transform:
      type: file
      description: Affine transform for initialization
      pattern: "*.{txt}"

  - deform_transform:
      type: file
      description: Deform transformation
      pattern: "*.{mgz}"

  - warped_image:
      type: file
      description: Warped image
      pattern: "*.{nii,.nii.gz}"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@scilus"
