---
name: "tracking_localtracking"
description: process local tracking
keywords:
  - Tractography
  - Local tracking
tools:
  - "Scilpy":
      ## TODO nf-core: Add a description and other details for the software below
      description: "The Sherbrooke Connectivity Imaging Lab (SCIL) Python dMRI processing toolbox."
      homepage: "https://github.com/scilus/scilpy.git"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  
  - fodf:
      type: file
      description: Nifti image of spherical harmonic file (fodf)
      pattern: "*.{nii,nii.gz}"

  - tracking_mask:
      type: file
      description: NIfti image binary mask for tracking
      pattern: "*.{nii,nii.gz}"

  - seed:
      type: file
      description: Nifti image seeding mask.
      pattern: "*.{nii,nii.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - trk:
      type: file
      description: Tractogram output file.
      pattern: "*.{trk,tck}"

  - config:
      type: file
      description: Json file containing tracking parameters.
      pattern: "*.{json}"

authors:
  - "@scilus"
