---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "segmentation_fslfirst"
description: Perform subcortical structure segmentation using FSL FIRST
keywords:
  - Segmentation
  - T1
  - Subcortical structures
tools:
  - "FSL":
      description: "FSL Toolbox"
      homepage: "https://fsl.fmrib.ox.ac.uk/fsl/fslwiki"

input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - image:
      type: file
      description: Nifti T1 volume to perform FIRST
      pattern: "*.{nii,nii.gz}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - subcortex_segmentation:
      type: file
      description: Nifti subcortex segmentation volume
      pattern: "*.{nii,nii.gz}"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@PaulBautin"

