name: Lint nf-scil module

on:
  workflow_dispatch:
    inputs:
      module:
        description: "A tag describing the module"
        required: true
        type: string
  workflow_call:
    inputs:
      module:
        description: "A tag describing the module"
        required: true
        type: string

run-name: Lint ${{ inputs.module }}
jobs:
  nf-core-lint:
    runs-on: ubuntu-latest
    name: nf-core-lint-${{ inputs.module }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install pip
        run: python -m pip install --upgrade pip

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Install nf-core tools
        run: |
          python -m pip install --upgrade --force-reinstall nf-core==2.14.*

      - name: Lint module ${{ inputs.module }}
        env:
          GIT_CLONE_PROTECTION_ACTIVE: false
        run: nf-core --verbose modules --git-remote https://github.com/scilus/nf-scil.git lint ${{ inputs.module }}
        if: ${{ !startsWith(inputs.module, 'subworkflows/') }}

      - name: Remove substring from matrix.tags
        id: remove_substring
        run: echo subworkflow_names=$(echo "${{ inputs.module }}" | sed 's/subworkflows\///g') >> $GITHUB_OUTPUT

      - name: Lint subworkflow ${{ inputs.module }}
        env:
          GIT_CLONE_PROTECTION_ACTIVE: false
        run: nf-core --verbose subworkflows --git-remote https://github.com/scilus/nf-scil.git lint ${{steps.remove_substring.outputs.subworkflow_names}}
        if: ${{ startsWith(inputs.module, 'subworkflows/') }}
