name: Lint nf-scil component

on:
  workflow_dispatch:
    inputs:
      component:
        description: "A tag describing the component"
        required: true
        type: string
      type:
        description: "Type of component"
        required: true
        type: choice
        options:
          - module
          - subworkflow
  workflow_call:
    inputs:
      component:
        description: "A tag describing the component"
        required: true
        type: string
      type:
        description: "Type of component"
        required: true
        type: string

run-name: Lint ${{ inputs.component }}
jobs:
  nf-core-lint:
    runs-on: ubuntu-latest
    name: nf-core-lint-${{ inputs.component }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
            ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install pip
        run: python -m pip install --upgrade pip

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Install nf-core tools
        run: |
          python -m pip install --upgrade --force-reinstall nf-core==2.14.*

      - name: Lint ${{ inputs.type }} ${{ inputs.component }}
        env:
          GIT_CLONE_PROTECTION_ACTIVE: false
        run: nf-core --verbose ${{ inputs.type }}s --git-remote https://github.com/scilus/nf-scil.git lint ${{ inputs.component }}
