---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "preproc_n4"
description: Bias field correction using N4
keywords:
  - "ANTs"
    description: ANTs computes high-dimensional mappings to capture the statistics of brain structure and function.

  - "scilpy"
    description: Scilpy is the main library supporting research and development at the Sherbrooke Connectivity Imaging Lab
tools:
  - "preproc":
      description: ""
      homepage: ""
      documentation: ""
      tool_dev_url: ""
      doi: ""
      licence: ""

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  
  - dwi:
      type: file
      description: Nifti image file to correct
      pattern: "*.{nii,nii.gz}"
  - b0:
      type: file
      description: Nifti image file - b0
      pattern: "*.{nii,nii.gz}"

  - b0_mask:
      type: file
      description: Nifti image file mask
      pattern: "*.{nii,nii.gz}"        

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - dwi:
      type: file
      description: DWI image N4 corrected
      pattern: "*.{nii,nii.gz}"

authors:
  - "@arnaudbore"
